# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mousemover.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(324, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(324, 240))
        MainWindow.setMaximumSize(QtCore.QSize(324, 240))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(150, 170, 161, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.startButton.setObjectName("startButton")
        self.gridLayout_2.addWidget(self.startButton, 0, 0, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.stopButton.setEnabled(False)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_2.addWidget(self.stopButton, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 301, 141))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 281, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timerEnabled = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.timerEnabled.setObjectName("timerEnabled")
        self.gridLayout_4.addWidget(self.timerEnabled, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 6, 1, 1)
        self.timerHour = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.timerHour.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timerHour.sizePolicy().hasHeightForWidth())
        self.timerHour.setSizePolicy(sizePolicy)
        self.timerHour.setObjectName("timerHour")
        self.gridLayout_5.addWidget(self.timerHour, 0, 1, 1, 1)
        self.timerMinute = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.timerMinute.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timerMinute.sizePolicy().hasHeightForWidth())
        self.timerMinute.setSizePolicy(sizePolicy)
        self.timerMinute.setMaximum(59)
        self.timerMinute.setObjectName("timerMinute")
        self.gridLayout_5.addWidget(self.timerMinute, 0, 3, 1, 1)
        self.timerSecond = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.timerSecond.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timerSecond.sizePolicy().hasHeightForWidth())
        self.timerSecond.setSizePolicy(sizePolicy)
        self.timerSecond.setMaximum(59)
        self.timerSecond.setObjectName("timerSecond")
        self.gridLayout_5.addWidget(self.timerSecond, 0, 5, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.randomMovementEnabled = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.randomMovementEnabled.setObjectName("randomMovementEnabled")
        self.verticalLayout.addWidget(self.randomMovementEnabled)
        self.randomDelayEnabled = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.randomDelayEnabled.setObjectName("randomDelayEnabled")
        self.verticalLayout.addWidget(self.randomDelayEnabled)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.minimizeToTrayEnabled = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.minimizeToTrayEnabled.setObjectName("minimizeToTrayEnabled")
        self.verticalLayout.addWidget(self.minimizeToTrayEnabled)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 170, 121, 31))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.currentTimerValue = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.currentTimerValue.setObjectName("currentTimerValue")
        self.gridLayout.addWidget(self.currentTimerValue, 0, 1, 1, 1)
        self.currentTimerLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.currentTimerLabel.setObjectName("currentTimerLabel")
        self.gridLayout.addWidget(self.currentTimerLabel, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 324, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdvanced_Settings = QtWidgets.QAction(MainWindow)
        self.actionAdvanced_Settings.setObjectName("actionAdvanced_Settings")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mouse Mover"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.timerEnabled.setText(_translate("MainWindow", "Enable Timer"))
        self.label_2.setText(_translate("MainWindow", "M"))
        self.label.setText(_translate("MainWindow", "H"))
        self.label_3.setText(_translate("MainWindow", "S"))
        self.randomMovementEnabled.setText(_translate("MainWindow", "Random Movement"))
        self.randomDelayEnabled.setText(_translate("MainWindow", "Random Delay Interval"))
        self.minimizeToTrayEnabled.setText(_translate("MainWindow", "Close Button Minimize to Tray"))
        self.currentTimerValue.setText(_translate("MainWindow", "00:00:00"))
        self.currentTimerLabel.setText(_translate("MainWindow", "Timer: "))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAdvanced_Settings.setText(_translate("MainWindow", "Advanced Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

